"""empty message

Revision ID: 4f4d4a9442f2
Revises: 
Create Date: 2021-04-13 20:20:37.391409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4d4a9442f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measuring_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=32), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measuring_set_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.String(length=32), nullable=True),
    sa.Column('sample_name', sa.String(length=32), nullable=True),
    sa.Column('operator', sa.String(length=32), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('vlazhnost', sa.Float(), nullable=True),
    sa.Column('atmosphere_pressure', sa.Float(), nullable=True),
    sa.Column('atmosphere_pressure_1', sa.Float(), nullable=True),
    sa.Column('graduation_name', sa.Integer(), nullable=True),
    sa.Column('graduation_time', sa.String(length=32), nullable=True),
    sa.Column('summarnyy_raskhod', sa.Float(), nullable=True),
    sa.Column('idk', sa.Float(), nullable=True),
    sa.Column('idk1', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('l_to_d', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['measuring_set_id'], ['measuring_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=32), nullable=True),
    sa.Column('finish_time', sa.String(length=32), nullable=True),
    sa.Column('p_p0', sa.Float(), nullable=True),
    sa.Column('peak_start', sa.Integer(), nullable=True),
    sa.Column('peak_finish', sa.Integer(), nullable=True),
    sa.Column('pick_max', sa.Integer(), nullable=True),
    sa.Column('pick_amplitude', sa.Float(), nullable=True),
    sa.Column('S_of_pick', sa.Float(), nullable=True),
    sa.Column('grad_koeff', sa.Float(), nullable=True),
    sa.Column('adsorb_or_desorb', sa.Integer(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['sample.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_point')
    op.drop_table('sample')
    op.drop_table('measuring_set')
    # ### end Alembic commands ###
